version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8 # Debian-based image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose  # Install docker-compose using apt
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
